/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package rsa

import java.math.BigInteger

class RSA(e: BigInteger, d: BigInteger, n: BigInteger) {

  def encrypt(message: Array[Byte]): Array[Byte] = {
   return new BigInteger(message).modPow(e, n).toByteArray
  }

  def decrypt(message: Array[Byte]): Array[Byte] = {
    return new BigInteger(message).modPow(d, n).toByteArray
  }
}
